In [253]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.stats.weightstats import ttest_ind
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.stats.api as sms
import statsmodels.api as sm

## Cleaning current DEM data (will be updated soon once proper data is acquired)

In [254]:
mjf_dem_raw_1 = pd.read_csv("raw DEM data/EP NO2 Aug+Sep 2025.csv")
mjf_dem_raw_2 = pd.read_csv("raw DEM data/MJF DEM cleaned.csv")

In [255]:
mjf_dem_raw_1.head()

          Date  NO2
0  8/1/25 3:00  1.4
1  8/1/25 4:00  1.3
2  8/1/25 5:00  2.1
3  8/1/25 6:00  2.7
4  8/1/25 7:00  3.5

In [256]:
mjf_dem_raw_2.head()

          datetime_est  no2    o3
0  2025-10-12 00:00:00  2.3  19.0
1  2025-10-12 01:00:00  2.0  21.2
2  2025-10-12 02:00:00  2.3  21.0
3  2025-10-12 03:00:00  1.7  23.0
4  2025-10-12 04:00:00  1.7  23.7

In [257]:
mjf_dem_raw_1 = mjf_dem_raw_1.rename(columns={"Date": "datetime_est", "NO2": "no2"})

#use mask to isolate midnight times, which by default do not have a 00:00:00 attached
mask = ~mjf_dem_raw_1["datetime_est"].str.contains(":", na=False)
mjf_dem_raw_1.loc[mask, "datetime_est"] = (mjf_dem_raw_1.loc[mask, "datetime_est"] + " 0:00")

#add empty o3 column for later merging
mjf_dem_raw_1["o3"] = pd.NA

mjf_dem_raw_1["datetime_est"] = pd.to_datetime(mjf_dem_raw_1["datetime_est"], format="%m/%d/%y %H:%M")

mjf_dem_raw_1.head(24)

          datetime_est   no2    o3
0  2025-08-01 03:00:00   1.4  <NA>
1  2025-08-01 04:00:00   1.3  <NA>
2  2025-08-01 05:00:00   2.1  <NA>
3  2025-08-01 06:00:00   2.7  <NA>
4  2025-08-01 07:00:00   3.5  <NA>
5  2025-08-01 08:00:00   2.9  <NA>
6  2025-08-01 09:00:00   1.6  <NA>
7  2025-08-01 10:00:00   1.2  <NA>
8  2025-08-01 11:00:00   1.3  <NA>
9  2025-08-01 12:00:00   1.0  <NA>
10 2025-08-01 13:00:00   1.0  <NA>
11 2025-08-01 14:00:00   0.9  <NA>
12 2025-08-01 15:00:00   1.0  <NA>
13 2025-08-01 16:00:00   1.0  <NA>
14 2025-08-01 17:00:00   1.2  <NA>
15 2025-08-01 18:00:00   1.6  <NA>
16 2025-08-01 19:00:00   3.5  <NA>
17 2025-08-01 20:00:00   5.3  <NA>
18 2025-08-01 21:00:00   9.3  <NA>
19 2025-08-01 22:00:00  12.6  <NA>
20 2025-08-01 23:00:00  11.4  <NA>
21 2025-08-02 00:00:00   7.9  <NA>
22 2025-08-02 01:00:00   6.2  <NA>
23 2025-08-02 02:00:00   6.2  <NA>

In [258]:
mjf_dem_raw_2["datetime_est"] = pd.to_datetime(mjf_dem_raw_2["datetime_est"])

mjf_dem_cleaned = pd.concat([mjf_dem_raw_1, mjf_dem_raw_2], ignore_index=True).sort_values("datetime_est")
mjf_dem_cleaned = mjf_dem_cleaned.reset_index(drop=True)

mjf_dem_cleaned.head(30)
mjf_dem_cleaned.to_csv("cleaned DEM data/dem_cleaned.csv", index=False)

/var/folders/cv/16s476bd69z2kjqnmm06ls5c0000gn/T/ipykernel_59832/849428465.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  mjf_dem_cleaned = pd.concat([mjf_dem_raw_1, mjf_dem_raw_2], ignore_index=True).sort_values("datetime_est")

## Cleaning quant data

In [259]:
dpw_raw = pd.read_csv("raw Quant data/dpw raw.csv")
mjf_raw = pd.read_csv("raw Quant data/mjf raw.csv")
mjf_recal = pd.read_csv("raw Quant data/mjf recalibrated.csv")
pema_raw = pd.read_csv("raw Quant data/pema raw.csv")
pha_raw = pd.read_csv("raw Quant data/pha raw.csv")

In [260]:
dpw_raw = (dpw_raw[["timestamp_local", "no2", "o3"]].rename(columns={"timestamp_local": "datetime_est"}))
dpw_raw["datetime_est"] = pd.to_datetime(dpw_raw["datetime_est"])

dpw_raw.head(30)

                datetime_est     no2      o3
0  2026-05-31 19:59:45+00:00  25.082  28.501
1  2026-05-31 19:58:45+00:00  24.654  29.081
2  2026-05-31 19:57:45+00:00  23.764  28.863
3  2026-05-31 19:56:45+00:00  22.344  28.328
4  2026-05-31 19:55:45+00:00  22.344  29.697
5  2026-05-31 19:54:45+00:00  25.490  27.914
6  2026-05-31 19:53:45+00:00  26.753  27.545
7  2026-05-31 19:52:45+00:00  25.143  29.443
8  2026-05-31 19:51:45+00:00  24.745  28.669
9  2026-05-31 19:50:45+00:00  25.224  29.005
10 2026-05-31 19:49:45+00:00  22.961  28.724
11 2026-05-31 19:48:45+00:00  23.433  29.954
12 2026-05-31 19:47:45+00:00  25.194  28.534
13 2026-05-31 19:46:45+00:00  21.842  30.331
14 2026-05-31 19:45:45+00:00  24.852  30.070
15 2026-05-31 19:44:45+00:00  24.807  28.223
16 2026-05-31 19:43:45+00:00  22.955  28.719
17 2026-05-31 19:42:45+00:00  24.452  28.828
18 2026-05-31 19:41:45+00:00  23.506  28.618
19 2026-05-31 19:40:45+00:00  22.989  28.741
20 2026-05-31 19:39:45+00:00  20.484  28.285
21 2026-05-31 19:38:45+00:00  23.428  28.117
22 2026-05-31 19:37:45+00:00  23.454  29.501
23 2026-05-31 19:36:45+00:00  24.403  27.874
24 2026-05-31 19:35:45+00:00  22.369  29.750
25 2026-05-31 19:34:45+00:00  22.351  28.367
26 2026-05-31 19:33:45+00:00  23.456  28.128
27 2026-05-31 19:32:45+00:00  23.506  28.158
28 2026-05-31 19:31:45+00:00  24.084  28.991
29 2026-05-31 19:30:45+00:00  19.678  28.007

In [261]:
dpw_quant_cleaned = (dpw_raw.set_index("datetime_est").resample("h").mean().reset_index())
dpw_quant_cleaned["datetime_est"] = dpw_quant_cleaned["datetime_est"].dt.tz_localize(None)

dpw_quant_cleaned.head()
dpw_quant_cleaned.to_csv("cleaned quant data/dpw_cleaned.csv", index=False)

In [262]:
mjf_raw = (mjf_raw[["timestamp_local", "no2", "o3"]].rename(columns={"timestamp_local": "datetime_est"}))
mjf_raw["datetime_est"] = pd.to_datetime(mjf_raw["datetime_est"])

mjf_raw.head(30)

                datetime_est    no2      o3
0  2026-05-31 19:59:46+00:00  4.040  43.102
1  2026-05-31 19:58:46+00:00  3.379  45.299
2  2026-05-31 19:57:46+00:00  4.023  43.554
3  2026-05-31 19:56:46+00:00  3.572  44.712
4  2026-05-31 19:55:46+00:00  3.577  45.183
5  2026-05-31 19:54:46+00:00  3.063  45.568
6  2026-05-31 19:53:46+00:00  3.394  44.873
7  2026-05-31 19:52:46+00:00  3.384  44.853
8  2026-05-31 19:51:46+00:00  4.007  44.484
9  2026-05-31 19:50:46+00:00  3.396  45.788
10 2026-05-31 19:49:46+00:00  3.245  46.846
11 2026-05-31 19:48:46+00:00  3.253  45.937
12 2026-05-31 19:47:46+00:00  3.393  45.327
13 2026-05-31 19:46:46+00:00  3.377  43.929
14 2026-05-31 19:45:46+00:00  3.389  44.864
15 2026-05-31 19:44:46+00:00  3.391  45.323
16 2026-05-31 19:43:46+00:00  3.391  45.779
17 2026-05-31 19:42:46+00:00  3.250  45.468
18 2026-05-31 19:41:46+00:00  3.414  45.360
19 2026-05-31 19:40:46+00:00  3.175  46.115
20 2026-05-31 19:39:46+00:00  3.277  45.950
21 2026-05-31 19:38:46+00:00  3.132  45.146
22 2026-05-31 19:37:46+00:00  3.351  42.970
23 2026-05-31 19:36:46+00:00  3.536  42.855
24 2026-05-31 19:35:46+00:00  3.729  43.654
25 2026-05-31 19:34:46+00:00  3.552  44.727
26 2026-05-31 19:33:46+00:00  3.249  44.539
27 2026-05-31 19:32:46+00:00  3.364  43.452
28 2026-05-31 19:31:46+00:00  3.942  42.611
29 2026-05-31 19:30:46+00:00  3.380  43.933

In [263]:
mjf_quant_cleaned1 = (mjf_raw.set_index("datetime_est").resample("h").mean().reset_index())
mjf_quant_cleaned1["datetime_est"] = mjf_quant_cleaned1["datetime_est"].dt.tz_localize(None)

mjf_quant_cleaned1.head()

         datetime_est        no2         o3
0 2026-03-10 20:00:00   8.700633  50.574533
1 2026-03-10 21:00:00  10.013767  44.751100
2 2026-03-10 22:00:00   6.648233  46.229233
3 2026-03-10 23:00:00   6.199550  42.575500
4 2026-03-11 00:00:00   7.638633  37.286617

In [264]:
#recalibrated historical data from the MJF quant needs to be averaged and combined with recent historical data
mjf_recal = (mjf_recal[["timestamp_local", "no2", "o3"]].rename(columns={"timestamp_local": "datetime_est"}))

#some recalibrated timestamps have thousandths of seconds included for some reason. Remove those here
mjf_recal["datetime_est"] = (mjf_recal["datetime_est"].astype(str).str.replace(r"\.000$", "", regex=True))
mjf_recal["datetime_est"] = (mjf_recal["datetime_est"].astype(str).str.replace(r"\.500$", "", regex=True))

mjf_recal["datetime_est"] = pd.to_datetime(mjf_recal["datetime_est"])

mjf_recal.head(30)

          datetime_est       no2          o3
0  2025-08-28 14:16:12 -5.594733  235.480795
1  2025-08-28 14:17:12 -5.594733  214.030878
2  2025-08-28 14:18:12 -5.594733  195.068412
3  2025-08-28 14:19:12 -5.594732 -261.291336
4  2025-08-28 14:20:12 -5.594324   61.186989
5  2025-08-28 14:21:12 -5.593890  102.366522
6  2025-08-28 14:22:12 -5.591060  105.408751
7  2025-08-28 14:23:12 -5.565535  102.416938
8  2025-08-28 14:24:12 -5.089504   99.235495
9  2025-08-28 14:25:12 -4.854538   94.138863
10 2025-08-28 14:26:12 -3.925403   93.196530
11 2025-08-28 14:27:12 -3.448501   86.839764
12 2025-08-28 14:28:12 -3.282005   84.029088
13 2025-08-28 14:29:12 -3.182774   80.575235
14 2025-08-28 14:30:12 -3.157581   78.462892
15 2025-08-28 14:31:12 -3.128792   76.365606
16 2025-08-28 14:32:12 -3.093669   74.460263
17 2025-08-28 14:33:12 -3.047799   71.742149
18 2025-08-28 14:34:12 -3.034699   70.105562
19 2025-08-28 14:35:12 -2.962147   69.007680
20 2025-08-28 14:36:12 -2.760739   68.166005
21 2025-08-28 14:37:12 -2.500362   66.894229
22 2025-08-28 14:38:12 -2.046517   66.468063
23 2025-08-28 14:39:12 -1.695154   65.274901
24 2025-08-28 14:40:12 -1.448254   65.195079
25 2025-08-28 14:41:12 -0.768009   65.117504
26 2025-08-28 14:42:12 -0.334673   64.625786
27 2025-08-28 14:43:12 -0.093219   63.527950
28 2025-08-28 14:44:12  0.233112   64.029869
29 2025-08-28 14:45:12  0.530892   63.007916

In [265]:
mjf_quant_cleaned2 = (mjf_recal.set_index("datetime_est").resample("h").mean().reset_index())
mjf_quant_cleaned2["datetime_est"] = mjf_quant_cleaned2["datetime_est"].dt.tz_localize(None)

mjf_quant_cleaned2.head()

         datetime_est       no2         o3
0 2025-08-28 14:00:00 -1.744937  73.771410
1 2025-08-28 15:00:00  2.202533  57.932656
2 2025-08-28 16:00:00  2.432583  56.728456
3 2025-08-28 17:00:00  2.577775  56.368741
4 2025-08-28 18:00:00  3.062726  57.325889

In [266]:
mjf_quant_cleaned = pd.concat([mjf_quant_cleaned2, mjf_quant_cleaned1], ignore_index=True)

#can't merge directly because there are slight floating point differences between concentrations between recalibrated data and data from the portal
#ensure preference of web portal data here so no merge issues (tho almost no difference anyways)
mjf_quant_cleaned = (mjf_quant_cleaned.drop_duplicates(subset="datetime_est", keep="last").sort_values("datetime_est").reset_index(drop=True))

mjf_quant_cleaned.to_csv("cleaned quant data/mjf_cleaned.csv")

mjf_quant_cleaned.head()

         datetime_est       no2         o3
0 2025-08-28 14:00:00 -1.744937  73.771410
1 2025-08-28 15:00:00  2.202533  57.932656
2 2025-08-28 16:00:00  2.432583  56.728456
3 2025-08-28 17:00:00  2.577775  56.368741
4 2025-08-28 18:00:00  3.062726  57.325889

In [267]:
pema_raw = (pema_raw[["timestamp_local", "no2", "o3"]].rename(columns={"timestamp_local": "datetime_est"}))
pema_raw["datetime_est"] = pd.to_datetime(pema_raw["datetime_est"])

pema_raw.head(30)

                datetime_est     no2      o3
0  2026-05-31 19:59:22+00:00  16.724  21.874
1  2026-05-31 19:58:22+00:00  16.719  21.425
2  2026-05-31 19:57:22+00:00  17.292  22.222
3  2026-05-31 19:56:22+00:00  16.697  21.455
4  2026-05-31 19:55:22+00:00  16.609  23.275
5  2026-05-31 19:54:22+00:00  16.027  22.950
6  2026-05-31 19:53:22+00:00  17.187  21.327
7  2026-05-31 19:52:22+00:00  16.622  21.436
8  2026-05-31 19:51:22+00:00  18.398  21.029
9  2026-05-31 19:50:22+00:00  17.214  21.746
10 2026-05-31 19:49:22+00:00  16.628  21.884
11 2026-05-31 19:48:22+00:00  17.796  20.711
12 2026-05-31 19:47:22+00:00  18.403  21.014
13 2026-05-31 19:46:22+00:00  19.009  20.449
14 2026-05-31 19:45:22+00:00  17.209  21.297
15 2026-05-31 19:44:22+00:00  18.395  21.036
16 2026-05-31 19:43:22+00:00  17.112  21.757
17 2026-05-31 19:42:22+00:00  17.688  20.728
18 2026-05-31 19:41:22+00:00  18.912  20.901
19 2026-05-31 19:40:22+00:00  18.303  21.480
20 2026-05-31 19:39:22+00:00  18.925  19.465
21 2026-05-31 19:38:22+00:00  19.538  19.791
22 2026-05-31 19:37:22+00:00  21.422  18.995
23 2026-05-31 19:36:22+00:00  18.906  20.923
24 2026-05-31 19:35:22+00:00  20.177  19.256
25 2026-05-31 19:34:22+00:00  20.795  20.015
26 2026-05-31 19:33:22+00:00  18.918  19.966
27 2026-05-31 19:32:22+00:00  19.542  20.740
28 2026-05-31 19:31:22+00:00  20.175  19.249
29 2026-05-31 19:30:22+00:00  21.408  19.436

In [268]:
pema_quant_cleaned = (pema_raw.set_index("datetime_est").resample("h").mean().reset_index())
pema_quant_cleaned["datetime_est"] = pema_quant_cleaned["datetime_est"].dt.tz_localize(None)

pema_quant_cleaned.head()
pema_quant_cleaned.to_csv("cleaned quant data/pema_cleaned.csv", index=False)

In [269]:
pha_raw = (pha_raw[["timestamp_local", "no2", "o3"]].rename(columns={"timestamp_local": "datetime_est"}))
pha_raw["datetime_est"] = pd.to_datetime(pha_raw["datetime_est"])

pha_raw.head(30)

                datetime_est     no2      o3
0  2026-05-31 19:59:26+00:00  22.540  14.699
1  2026-05-31 19:58:26+00:00  23.036  15.473
2  2026-05-31 19:57:26+00:00  23.073  14.127
3  2026-05-31 19:56:26+00:00  21.967  15.263
4  2026-05-31 19:55:26+00:00  20.787  15.539
5  2026-05-31 19:54:26+00:00  23.023  15.466
6  2026-05-31 19:53:26+00:00  25.336  13.952
7  2026-05-31 19:52:26+00:00  24.520  14.228
8  2026-05-31 19:51:26+00:00  24.976  14.093
9  2026-05-31 19:50:26+00:00  23.648  14.956
10 2026-05-31 19:49:26+00:00  25.050  14.586
11 2026-05-31 19:48:26+00:00  24.217  16.246
12 2026-05-31 19:47:26+00:00  23.763  16.848
13 2026-05-31 19:46:26+00:00  23.294  17.008
14 2026-05-31 19:45:26+00:00  24.394  17.711
15 2026-05-31 19:44:26+00:00  20.757  18.929
16 2026-05-31 19:43:26+00:00  23.381  19.348
17 2026-05-31 19:42:26+00:00  20.754  20.784
18 2026-05-31 19:41:26+00:00  20.024  18.626
19 2026-05-31 19:40:26+00:00  22.825  18.589
20 2026-05-31 19:39:26+00:00  22.164  18.698
21 2026-05-31 19:38:26+00:00  22.180  19.632
22 2026-05-31 19:37:26+00:00  22.213  20.141
23 2026-05-31 19:36:26+00:00  21.490  20.308
24 2026-05-31 19:35:26+00:00  20.721  19.968
25 2026-05-31 19:34:26+00:00  20.703  20.910
26 2026-05-31 19:33:26+00:00  18.422  20.390
27 2026-05-31 19:32:26+00:00  17.139  20.621
28 2026-05-31 19:31:26+00:00  18.588  16.629
29 2026-05-31 19:30:26+00:00  24.285  14.003

In [270]:
pha_quant_cleaned = (pha_raw.set_index("datetime_est").resample("h").mean().reset_index())
pha_quant_cleaned["datetime_est"] = pha_quant_cleaned["datetime_est"].dt.tz_localize(None)

pha_quant_cleaned.head()
pha_quant_cleaned.to_csv("cleaned quant data/pha_cleaned.csv", index=False)